language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- ./can_auto_deploy.sh && mvn deploy --settings settings.xml
env:
  global:
  - secure: bYF1lGm/W8DSph3GvIlexgHOsR3pwyUHPdODj7FnUa4qpo/MSHtmLCf+tdaOdu5WDzp1fnSL8anKe35xhxsE0ovw/qQkQktyQjTV8IfFwk+naQihfQABADDBAtRT5gNTX5v9v6s4K9wfh3i9Eg3UowKHr/4U3LPwJdumZLB1lWOE3IGLIK00OMRQCYVCOWjhp9znszkW0pJSdmRGZxFTcarStSYoSywIB0/qu8LzoFl6u4Y9+9EO1i0VJpO0kcftK+Ac/NPtQ+srA87T4xz7lv9t7tMHK8EaK4NMcBMcKDz77esawb4MEyKJZ5ZnhCt9u+d51Ti9YRBXg2RJBGIpOudNoc7kuI3EAFWCSaMZBuWFGLgzIhR4P56rqSc2KNqO2MW7Dnt9tcovlHC+/xxukliQ88FLIBd+6MXSnoOs5oB1N15MOVabRi8ou/Z5zG3f2+6VAv2AfjmLQpu/5fOmvn+was+bFQreNVGky+tkwQprK00SND6kRN+f+QTyY2nG9KZLHjGEyQqBof5WMZbgY5RL73HsibWjMy3/GeuKPmKg+MgG3NN9gpuf3bgSzIwcFRj/yyELIlZQkbp6ejIer26HHtpRjtRfXdUFlIU4u4j/3wHdCMGqZJTYeHDYUGeadFwCZ+JVTinHSkthOnXex+dso8Ip1QXYRRZs5dT5uiU=
  - secure: WIL8uDRuP2ZbFR8C3Y9FjU+I1hnmOUHGIu7SjcBuTeuv/9AT6Z4s8Ojj+2LNJVMu0wixwftB4LVacS/qTvKkcwyTikCFzZK8NkhAHcUEo/oLq/cQyDIqjNMvGeWjuxj9Q/sQIcUPktfq19WNZsDJA2Ti+YzhQ4k4dTA+stWDWjGmtiVuWvCDYzJcibD2sndDjdGa9Y02jRT1EfJhvPvCz8w8cl1hD5jMj81atbUcwJ068zGUNO/7a3832u9dwUuA1lF/cebwT1/oRmuD1CepqDQFgfc6EaSlrqO2SKH9/6UlYMta3hAccpHuswPykmZJ0bGaCMhEyEkLI78g/zpKyXEQsUBlHCLfRQdKX0SvRq9RoZCyfl9Jy5jrWZKxf8ShOT1pnbo9PqGu2al6VXJc27C2HCB9YcZR9pg/z+ylgQVSi5GuK3qYP5iRAMABoM/ZsplCW77HLkUFsOyKdBMKPjiea+sIF4hh1XUQdPupThdAGH6XaxsHBeJKMIZLKsyMsHDc0HkPDoJ25BP6z39RCslEQCQI5YbYa5HfFb1Tw8CaWzpBlbcfFekruE4lXInnK6bgpMHI88oyFGHUVXcSp8smSp9JQrNZyMJfnMm/+tJBvmEO60O2PHZ66r2IzlPFjIaYaQScI3VrXV9Zn/fHiss76FTM8gQlYNPKjpLoE6Q=
